apiVersion: apps/v1
kind: Deployment
metadata:
  name: ssa-frontend
spec:
  replicas: 1 # 실행할 파드 개수
  selector:
    matchLabels:
      app: ssa-frontend
  template:
    metadata:
      labels:
        app: ssa-frontend
    spec:
      containers:
        - name: ssa-frontend
          image: asia-northeast3-docker.pkg.dev/ku-ngds-ssa-478004/ku-ngds-ssa-registry/ssa-frontend:latest
          ports:
            - containerPort: 80 # Dockerfile에서 EXPOSE한 포트
---
apiVersion: v1
kind: Service
metadata:
  name: ssa-frontend-service
spec:
  type: LoadBalancer # 외부 IP를 받기 위해 LoadBalancer 사용
  selector:
    app: ssa-frontend
  ports:
    - protocol: TCP
      port: 80       # 외부에서 접속할 포트
      targetPort: 80 # 컨테이너 내부 포트